---
- name: Sync repository to master
  hosts: MASTER
  become: no

  tasks:
    - name: Pull github repository
      git:
        repo: "{{ git_repository }}"
        key_file: "{{ git_key }}"
        version: "{{ git_branch }}"
        dest: "{{ git_local_folder }}"
        clone: no
        update: yes


