---
- name: Sync repository to master
  hosts: MASTER
  become: no

  tasks:
    - name: Pull github repository
      git:
        repo: "{{ git_repository}}"
        version: "{{ git_branch }}"
        dest: "{{ git_local_folder }}"
        update: yes


