---
- name: Deploy NGINX
  hosts: PC1

  tasks:
    - name: Ensure if web service is started
          service:
            name: nginx
            state: stopped

    - name: Remove WEB server
      apt:
        name: nginx
        state: absent
        purge: yes


- name: Remove DB
  hosts: PC2

  tasks:
    - name: Ensure if postgesql service is started
        service:
          name: postgresql
          state: stopped

    - name: Remove Postgesql
      apt:
        name: postgresql
        state: absent
        purge: yes

