---
- name: Sync repository to master
  hosts: MASTER
  become: yes

  tasks:
    - name: Pull github repository
      git:
        repo: "{{ git_repository }}"
        version: "{{ git_branch }}"
        dest: "{{ git_local_folder }}"
        key_file: "{{ git_key_user }}"
        clone: no
        update: yes
      become_user: "{{ git_pull_user }}"

