---
- name: Set maven on server
  hosts: PC2
  become: yes
  vars:
    maven_env:
      - key: 'M2_HOME'
        value: '/opt/maven'
      - key: 'MAVEN_HOME'
        value: '/opt/maven'
      - key: 'PATH'
        value: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:${M2_HOME}/bin:${PATH}'

  tasks:
    - name: Set env for maven
      ansible.builtin.lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_items: "{{ maven_env }}"

#- name: Sync repository to master(this is strange, but i just less)
#  hosts: MASTER
#  become: no

#  tasks:
#    - name: Pull github repository
#      git:
#        repo: "{{ git_repository}}"
#        version: "{{ git_branch }}"
#        dest: "{{ git_local_folder }}"
#        update: yes