---
- name: Sync repository to master
  hosts: MASTER

  tasks:
    - name: Pull github repository
      git:
        repo: git@github.com:PhantomMad/HW8.git
        version: develop
        dest: /etc/ansible
        clone: no
        update: yes


